#pragma once
vector<Orders> orders;
vector<Driver> driver;
vector<Car> car;
string Dfile = "Driversfile.txt";
string Cfile = "Carfile.txt";
string Ofile = "Ordersfile.txt";

void titul();
void menu();
void menuDrivers(int choose);
void getData(vector<Driver>& driver);
string infoSet(vector<Driver>& driver, string userName, string infonew, int choose);
void update(vector<Driver> drivers);
void addtofile(string username, string stazh, string number, string car, string phonenum);
string delfromfile(vector<Driver> driver, string userName);
void getData(vector<Car>& car);
void carmenu(int choose);
string infoSet(vector<Car>& car, string mark, string infonew, int choose);
void update(vector<Car> car);
void getData(vector<Car>& car);
void addtofile(string mark, string model, string num, string color, string year, string mileage, string hp, string consum);
string delfromfile(vector<Car> car, string mark);
void ordermenu(int choose);
string delfromfile(vector<Orders> orders, string time);
void addtofile(string cFIO, string time, string to, string from, string driver, string price, string avto);
void update(vector<Orders> orders);
void getData(vector<Orders>& orders);
void alldriver();
int changedriver(int choose);
void adddriver();
void delDriver();
void allCars();
int changecar(int choose);
void addCar();
void delCar();
void allOrders();
int addOrder();
void delOrder();
int changeOrder(int choose);
string infoSet(vector<Orders>& order, string time, string infonew, int choose);